name: Bug Report
description: Report a runtime or API bug.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: "Use this template for functional bugs and runtime errors."
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Provide exact steps and code snippet.
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: triode Version / Tag
      placeholder: "v1.4.1 or commit SHA"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser + Version
      placeholder: "Chrome 122, Firefox 123"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS + Version
      placeholder: "macOS 14.4, Windows 11"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console Errors / Logs
      render: shell
